### ISSUE TITLE
Button?

### ISSUE THREAD

**Issue by ryanknutson** [howderek/howderek.github.io#1]
Hey it's Ryan from FBLA! Nice job for the win!

About this issue, your "Lets get in touch" button doesn't link to anything. You might want to fix that or remove the hover cursor.

**Comment by howderek** [comment]
It's a mailto: link so you may not have a mail client configured, but thank you for your feedback!

I'm still in the process of migrating to GitHub pages from shared Apache hosting, so I still have a few kinks to work out but I'll be fully transitioned soon!
